### PR TITLE
usability updates to readme

### PR DESCRIPTION
**Pull request by whatSocks**
* added .env-example file so users wouldn't have to copy from readme to get started
* added `cd rxc-voice` to setup instructions so users would be in the correct directory
* added some formatting
* added example docker command so new users could copy+paste to see if things are working
* deleted .DS_Store

### CODE REVIEW

**Comment by alexrandaccio** [comment]
made small tweaks to your additions to the README @whatSocks, just for clarity. Thanks for your input! I haven't had much time to focus on documentation yet, so your contributions are much appreciated.

**Review by alexrandaccio — APPROVED** [review]
@whatSocks feel free to merge this, or leave it open if you think more changes should be made

**Comment by whatSocks** [comment]
@alexrandaccio I don't have merge rights to this repo ;)

**Comment by alexrandaccio** [comment]
> @alexrandaccio I don't have merge rights to this repo ;)

my bad, I'll merge it myself

> another change that would be good to make (here or separately) would be to not version control `rxc-voice/src/utils/urls.ts` but have another example file so when the developer changes it it doesn't mess up the version control

totally agree, this is something I've been putting off doing for a while

**Pull request merged**
